### ISSUE TITLE
Broken Syntax Highlighting

### ISSUE THREAD

**Issue by dnldd** [atom/language-go#131] opened 2017-07-11 11:02 UTC
The syntax highlighting for golang in atom 1.18.0 seems buggy, in the image below I'm using squirrel to create an SQL query, the syntax highlighting fails when string literals are introduced. It treats everything as a string literal (light green highlight) from there on, disregarding quote marks.

<img width="837" alt="broken-syntax-highlighting" src="https://user-images.githubusercontent.com/1281030/28065322-975bddfe-6627-11e7-9732-4b3d03cdc9ea.png">

**Comment by 50Wliu** [comment] 2017-07-11 14:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/atom#1667. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-07-11 14:54 UTC
