### ISSUE TITLE
Comment in import is not highlighted

### ISSUE THREAD

**Issue by ramya-rao-a** [atom/language-go#115] opened 2017-03-05 06:56 UTC
_From @vy0b0x on March 4, 2017 8:52_

VSCode version: 1.10.1
vscode-go version: 0.6.55
![1](https://cloud.githubusercontent.com/assets/5011191/23577480/e1a14044-00fa-11e7-98d0-cb03ccf1139e.png)

_Copied from original issue: Microsoft/vscode-go#839_

**Comment by joefitzgerald** [comment] 2017-03-05 18:04
👋 Hi @ramya-rao-a. Looks like you've taken over much of the work on the https://github.com/microsoft/vscode-go project; as the maintainer of https://github.com/joefitzgerald/go-plus project I have a lot of respect for the work you're doing.

I have noticed a pattern where grammar-related issues are identified in the `vscode-go` repo and "moved" here, unmodified. In talking with the Atom maintainers, this has occurred on other grammars (e.g. [`language-c`](https://github.com/atom/language-c/issues?utf8=%E2%9C%93&q=author%3Aaeschli)).

Going forward, I would love to establish some ways for us to work together on this grammar, and to avoid "moving" issues from the vscode-go repo without any further involvement from the Microsoft team. Here are some ideas:

* It would be great if you could test a given issue in `atom` itself, and validate that the issue is experienced in Atom prior to opening the issue here (ideally you would include a screenshot from both applications, with steps for reproduction). In many / most cases the issue will be present in both but there may be slight differences between the two applications that will be evident when this additional testing is done
* It would be helpful to include are currently identified for the text in question, and the scopes expected for the text in question (e.g. actual: `.source.go` / expected: `.source.go .comment`) 
* It would be wonderful if you would consider contributing to the `language-go` package via pull requests. This is absolutely an option that is available to you and it would be helpful for all to have additional engineering time spent on this package.
* If you would like, I am open to a regular call between us to discuss shared issues and keep focus on them so we can work toward resolution.

**Comment by joefitzgerald** [comment] 2017-03-05 19:03
This issue is a duplicate of https://github.com/atom/language-go/issues/105 which itself is a duplicate of https://github.com/atom/language-go/issues/102, which was fixed in https://github.com/atom/language-go/pulls/107.

**Closed by joefitzgerald** 2017-03-05 19:03 UTC

**Comment by vy0b0x** [comment] 2017-03-05 23:41
Thank for your answer

**Comment by ramya-rao-a** [comment] 2017-03-06 01:52
Hey @joefitzgerald,

I am definitely up for a standard way of reporting grammar related issues from vscode-go

Trying to repro the same in atom seems logical, vscode might be behind in using the latest grammar

Adding the scope identified for the text in question: yes, definitely.

About contributing back to the grammar itself: I always wanted to do this, just didn't get time to begin :) Will start looking into it soon though

As of now #103 is the only open issue moved from vscode-go. So regular call needed, but happy to know I can reach out to you in the future if more issues pop up

Thanks!
