### ISSUE TITLE
Language-go package seems to not work

### ISSUE THREAD

**Issue by qhenkart** [atom/language-go#162] opened 2018-11-05 03:54 UTC
### Description

Language-Go not working:

Language go stopped adding any go classes or go specific formatting to my files. It looks like an update of some sort occurred in the middle of my work and suddenly all of my styling broke.

I have done a complete 100% fresh install of Atom, and I am still getting the same issue. There are no go specific classes and the tags that I see from the go.cson file which were working previously are no longer being added (for example, "%v" does not have any special formatting)

I suspect some dependency broke or I am missing some setting that requires some terminal command.

### Steps to Reproduce

1. Completely uninstall Atom (including all support files and locations
2. Install atom
3. open up a file with --dev and notice that there are no go specific class tags and no formatting on any go specific input

**Expected behavior:** Go specific grammar should have go specific tags or classes

**Actual behavior:** nothing happens, something is broken

**Reproduces how often:** 100% on my machine

### Versions

MacOS Mojave 10.14
```
Atom    : 1.32.1
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
```
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.1
python 2.7.15
git 2.17.1
```

**Comment by thomasjo** [comment] 2018-11-05 11:59
Duplicate of #159. Fixed by #160. The fix will most likely be available in the next patch release of Atom 1.32.

**Closed by thomasjo** 2018-11-05 11:59 UTC
