### ISSUE TITLE
Comments inside the import block are not highlighted

### ISSUE THREAD

**Issue by ramya-rao-a** [atom/language-go#105] opened 2016-12-26 15:31 UTC
_From @ahmetalpbalkan on December 21, 2016 17:52_

![image](https://cloud.githubusercontent.com/assets/159209/21400087/3439cf6e-c763-11e6-98b8-92ff35b49655.png)

_Copied from original issue: Microsoft/vscode-go#694_

**Comment by 50Wliu** [comment] 2016-12-31 00:59
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #102. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-12-31 00:59 UTC
