### ISSUE TITLE
Printf("message %s\n", str) => " is doubled when type \n

### ISSUE THREAD

**Issue by cpro95** [atom/language-go#99] opened 2016-10-18 06:24 UTC
Printf("message %s\n", str)

In upper code,  when typing \n and " , " doubled two times.
it agonize me.
fix this plz

**Comment by 50Wliu** [comment] 2016-10-18 15:23
This is a duplicate of atom/bracket-matcher#80 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-10-18 15:23 UTC
